services:
  mysql-development:
    image: mysql
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: y
      MYSQL_DATABASE: beers_api
    ports:
      - "3308:3306"