server:
  address: ":8080"
  timeout: 100

database:
  url: root:@tcp(localhost:3308)/beers_api?parseTime=true
  maxIdleConns: 5
  maxOpenConns: 50
  connMaxLifetime: 60
  autoMigrate: true
logger:
  level: "debug"